
cookies:
  # æ˜¯å¦ä½¿ç”¨è¿™ä¸ª cookieï¼Œå¦‚æœå¯ç”¨ï¼Œä¸ä¼šè‡ªåŠ¨è·å–æœ€æ–° cookieï¼Œlinux ä¸Šé¢ä¸º trueï¼Œå› ä¸ºä¸èƒ½æ‰“å¼€ç½‘é¡µè·å–ğŸ˜
  enable: false
  rail_expiration: "1576330253758"
  rail_deviceid: "D0vKZrOYYR8LWwpDIMmErxMPQ_weK4SG8vBGv_hk-Hl7iOEpGACn8QqbxAPren7my5aAozndcRPaNV0lhBepXDUVe_AEWyYmahcm75ZViUV_Ty6NbfVO20fWgQhNPSkAj5anYugDWT1drqVO9GRLv6vfHrVSbGJE"
